// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using АПТ_Core.Data;

namespace АПТ_Core.Migrations
{
    [DbContext(typeof(TehContext))]
    [Migration("20220212014456_TehMig1")]
    partial class TehMig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("АПТ_Core.Models.Stud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Im")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rost")
                        .HasColumnType("int");

                    b.Property<decimal>("St_Ball")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stipendiya")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stud");
                });

            modelBuilder.Entity("АПТ_Core.Models.Teach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Im")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rost")
                        .HasColumnType("int");

                    b.Property<decimal>("ZarPlata")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Teach");
                });
#pragma warning restore 612, 618
        }
    }
}
